# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuickDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickDemo

  target 'QuickDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    pod 'RainbowSwift'
  end

end
